version: '3'
services:
  mongo:
    image: 'mongo'
    container_name: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=udemy-ng-node
      - MONGO_INITDB_ROOT_USERNAME=root-user
      - MONGO_INITDB_ROOT_PASSWORD=P@ssw0rd1
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - d:/mongo-data:/data/db
    ports:
      - '27017-27019:27017-27019'
    networks:
      - udemy-ng-nodejs

  server-ui:
    image: ${DOCKER_REGISTRY-}server-ui
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '4200:4200'
    networks:
      - udemy-ng-nodejs

networks:
  udemy-ng-nodejs:
    name: udemy-ng-nodejs
